sudo: false
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
install: true
jdk: oraclejdk8
language: java
before_script:
- ./gradlew --version
script:
- ./gradlew -S -Dscan build jacocoTestReport jacocoRootReport
after_success:
- ./gradlew coveralls
